In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [10]:
df.shape

(5572, 3)

In [5]:
df['spam'] = df.Category.apply(lambda x: 1 if x=='spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [11]:
x_train.shape

(4457,)

In [12]:
x_test.shape

(1115,)

In [13]:
type(x_train)

pandas.core.series.Series

In [14]:
x_train[:4]

2882    Printer is cool. I mean groovy. Wine is groovying
3162    Mystery solved! Just opened my email and he's ...
2163    1) Go to write msg 2) Put on Dictionary mode 3...
2630    Hey there! Glad u r better now. I hear u treat...
Name: Message, dtype: object

In [15]:
x_train[:4][2882]

'Printer is cool. I mean groovy. Wine is groovying'

In [16]:
y_train[:4]

2882    0
3162    0
2163    0
2630    0
Name: spam, dtype: int64

In [19]:
type(x_train.values)

numpy.ndarray

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

In [20]:
x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59233 stored elements and shape (4457, 7750)>

In [21]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7750))

In [22]:
x_train_cv.shape

(4457, 7750)

In [38]:
v.get_feature_names_out()[1999]

'cool'

In [24]:
v.get_feature_names_out().shape

(7750,)

In [25]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [26]:
v.vocabulary_

{'printer': 5421,
 'is': 3731,
 'cool': 1999,
 'mean': 4395,
 'groovy': 3236,
 'wine': 7537,
 'groovying': 3237,
 'mystery': 4660,
 'solved': 6309,
 'just': 3856,
 'opened': 4945,
 'my': 4653,
 'email': 2552,
 'and': 965,
 'he': 3352,
 'sent': 6034,
 'me': 4393,
 'another': 985,
 'batch': 1245,
 'isn': 3737,
 'sweetie': 6666,
 'go': 3147,
 'to': 6942,
 'write': 7627,
 'msg': 4606,
 'put': 5511,
 'on': 4923,
 'dictionary': 2286,
 'mode': 4542,
 'cover': 2039,
 'the': 6825,
 'screen': 5971,
 'with': 7554,
 'hand': 3298,
 'press': 5398,
 'lt': 4230,
 'gt': 3249,
 'gently': 3097,
 'remove': 5704,
 'ur': 7203,
 'its': 3749,
 'interesting': 3697,
 'hey': 3407,
 'there': 6840,
 'glad': 3134,
 'better': 1326,
 'now': 4828,
 'hear': 3363,
 'treated': 7039,
 'urself': 7216,
 'digi': 2303,
 'cam': 1621,
 'it': 3742,
 'good': 3170,
 'we': 7423,
 'off': 4880,
 'at': 1121,
 '9pm': 745,
 'have': 3345,
 'fab': 2722,
 'new': 4748,
 'year': 7686,
 'in': 3631,
 'coupla': 2031,
 'wks': 7568,
 'no': 4784,


In [27]:
v.get_feature_names_out()[5421]

'printer'

In [30]:
x_train_np = x_train_cv.toarray()
x_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7750,))

In [31]:
np.where(x_train_np[0]!=0)

(array([1999, 3236, 3237, 3731, 4395, 5421, 7537]),)

In [43]:
x_train[0]

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [34]:
x_train_np[0][1999]

np.int64(1)

In [44]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
model= MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [46]:
x_test_cv= v.transform(x_test)

In [47]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       970
           1       0.96      0.89      0.92       145

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [48]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_cv = v.transform(emails)
model.predict(emails_cv)

array([0, 1])

In [49]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [50]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [51]:
print(classification_report(y_test, clf.predict(x_test)))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       970
           1       0.96      0.89      0.92       145

    accuracy                           0.98      1115
   macro avg       0.97      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115

